# Generated by Django 3.0.4 on 2020-03-11 18:32

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='От')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='До')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson',
                                   verbose_name='Обслуживаемый')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='visits.Visitor', verbose_name='Родственник')),
            ],
            options={
                'verbose_name': 'Поездка обслуживаемого',
                'verbose_name_plural': 'Поездки обслуживаемых',
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='От')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='До')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('diagnose', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson',
                                   verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Больничный',
                'verbose_name_plural': 'Больничные',
            },
        ),
    ]
