# Generated by Django 2.1.7 on 2020-02-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaving', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sickleave',
            options={'verbose_name': 'Больничный', 'verbose_name_plural': 'Больничные'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Поездка обслуживаемого', 'verbose_name_plural': 'Поездки обслуживаемых'},
        ),
    ]
