# Generated by Django 2.1.7 on 2020-03-11 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
                ('receptionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition', verbose_name='Ответственный администратор')),
            ],
            options={
                'verbose_name': 'Ночная смена',
                'verbose_name_plural': 'Ночные смены',
            },
        ),
        migrations.CreateModel(
            name='ServicedPersonOvernight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.NightShift', verbose_name='Ночь')),
                ('serviced_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson', verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Ночующий в отделении обслуживаемый',
                'verbose_name_plural': 'Ночующие в отделении обслуживаемые',
            },
        ),
        migrations.CreateModel(
            name='VisitorOvernight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.NightShift', verbose_name='Ночь')),
                ('serviced_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visitor', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Ночующий в отделении посетитель',
                'verbose_name_plural': 'Ночующие в отделении посетители',
            },
        ),
    ]
