# Generated by Django 2.1.7 on 2020-03-11 16:30

import applications.core.enums
import applications.core.utils.datetime
import applications.social_work.enums
import applications.social_work.models.services
import choicesenum.django.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Включенная в ИППСУ услуга',
                'verbose_name_plural': 'Включенные в ИППСУ услуги',
            },
        ),
        migrations.CreateModel(
            name='IPPSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(default=applications.core.utils.datetime.later_3_years, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False, help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления ИППСУ', verbose_name='В архиве')),
                ('serviced_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson', verbose_name='Обслуживаемый')),
                ('social_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.WorkerPosition', verbose_name='Социальный работник')),
            ],
            options={
                'verbose_name': 'ИППСУ',
                'verbose_name_plural': 'ИППСУ',
            },
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата оказания')),
                ('type_of_service', choicesenum.django.fields.EnumCharField(default='U', editable=False, enum=applications.core.enums.ServiceTypeEnum, max_length=1, verbose_name='Тип')),
                ('volume', models.FloatField(default=1.0, verbose_name='Оказанный объем услуги')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество услуг')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
        ),
        migrations.CreateModel(
            name='ProvidedServiceJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=applications.core.utils.datetime.month_start, verbose_name='Период от')),
                ('date_to', models.DateField(default=applications.core.utils.datetime.month_end, verbose_name='Период до')),
                ('ippsu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services_journals', to='social_work.IPPSU', verbose_name='ИППСУ')),
            ],
            options={
                'verbose_name': 'Журнал оказанных услуг',
                'verbose_name_plural': 'Журналы оказанных услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512, verbose_name='Наименование')),
                ('type_of_service', choicesenum.django.fields.EnumCharField(default='U', enum=applications.core.enums.ServiceTypeEnum, max_length=1, verbose_name='Тип')),
                ('service_category', models.CharField(choices=[('SB', 'Социально-бытовые услуги'), ('ME', 'Социально-медицинские услуги'), ('PS', 'Социально-психологические услуги'), ('ED', 'Социально-педагогические услуги'), ('WO', 'Социально-трудовые услуги'), ('LA', 'Социально-правовые услуги'), ('CO', 'Услуги в целях повышения коммуникативного потенциала получателей социальных услуг имеющих ограничения жизнедеятельности, в том числе детей-инвалидов'), ('QU', 'Срочные социальные услуги'), ('OT', '-Прочие'), ('UN', 'Не указано')], default='UN', max_length=2, verbose_name='Категория')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('time_for_service', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество рабочего времени (мин)')),
                ('place', models.CharField(choices=[('H', 'на дому'), ('O', 'в организации (полустационар)'), ('-', 'повсеместно')], default='-', max_length=1, verbose_name='Место оказания')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Единица измерения')),
                ('period', choicesenum.django.fields.EnumCharField(blank=True, default=None, enum=applications.social_work.enums.PeriodEnum, help_text='Установите показатель, только если требуется ограничить услугу по частоте оказания (условие периодичности)', max_length=1, null=True, verbose_name='В срок')),
            ],
            options={
                'verbose_name': 'Единица измерения услуги',
                'verbose_name_plural': 'Единицы измерения услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False, help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления услуги', verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Перечень услуг',
                'verbose_name_plural': 'Перечни услуг',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', choicesenum.django.fields.EnumCharField(default=0, enum=applications.social_work.enums.StatementEnum, max_length=1, verbose_name='Логический оператор')),
                ('limit', models.FloatField(default=1, verbose_name='Ограничение')),
            ],
            options={
                'verbose_name': 'Условие для услуги',
                'verbose_name_plural': 'Условия для услуг',
            },
        ),
        migrations.AddField(
            model_name='servicemeasurement',
            name='period_statement',
            field=models.ForeignKey(blank=True, default=applications.social_work.models.services.default_statement, help_text='Ограничевает оказание услуги по количеству (раз) в указанный период', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_by_period', to='social_work.Statement', verbose_name='Условие периодичности'),
        ),
        migrations.AddField(
            model_name='servicemeasurement',
            name='volume_statement',
            field=models.ForeignKey(blank=True, default=applications.social_work.models.services.default_statement, help_text='Ограничевает объем услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_by_volume', to='social_work.Statement', verbose_name='Условие превышения объема'),
        ),
        migrations.AddField(
            model_name='service',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.ServiceMeasurement', verbose_name='Единица измерения (периодизация)'),
        ),
        migrations.AddField(
            model_name='service',
            name='services_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.ServicesList', verbose_name='Перечень услуг'),
        ),
        migrations.AddField(
            model_name='providedservice',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='social_work.ProvidedServiceJournal', verbose_name='Журнал оказанных услуг'),
        ),
        migrations.AddField(
            model_name='providedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.Service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='IPPSU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_services', to='social_work.IPPSU', verbose_name='ИППСУ'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.Service', verbose_name='Услуга'),
        ),
    ]
