# Generated by Django 2.1.7 on 2019-06-06 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_position_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('W', 'Неделя'), ('M', 'Месяц'), ('H', 'Полугодие'), ('Y', 'Год')], max_length=1, verbose_name='Тип периода')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Периодизация услуги',
                'verbose_name_plural': 'Периодизация услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512, verbose_name='Название')),
                ('service_category', models.CharField(choices=[('SB', 'Социальная'), ('PS', 'Психологическая'), ('OT', '-Прочие')], max_length=2, verbose_name='Категория')),
                ('type_of_service', models.CharField(choices=[('G', 'Гарантированная'), ('A', 'Дополнительная'), ('P', 'Платная')], max_length=1, verbose_name='Тип')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_work.Period', verbose_name='Периодизация')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата оказания')),
                ('type_of_service', models.CharField(blank=True, choices=[('G', 'Гарантированная'), ('A', 'Дополнительная'), ('P', 'Платная')], max_length=1, verbose_name='Тип услуги')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition', verbose_name='Социальный работник')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.Service', verbose_name='Услуга')),
                ('serviced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson', verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=92, verbose_name='Стоимость')),
                ('date_in', models.DateTimeField(default=datetime.datetime.now, verbose_name='Действие тарифа от')),
                ('date_out', models.DateTimeField(help_text='Можно оставить пустым, если тариф действует до сих пор', null=True, verbose_name='Действие тарифа до')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.Service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Тариф услуги',
                'verbose_name_plural': 'Тарифы услуг',
            },
        ),
    ]
