# Generated by Django 2.1.7 on 2019-09-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(choices=[('R', 'раз'), ('Q', 'кв-я'), ('M', 'кв. м.'), ('C', 'час'), ('B', 'бл-о')], max_length=1, verbose_name='Единица измерения')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('period', models.CharField(blank=True, choices=[('D', 'День'), ('W', 'Неделю'), ('M', 'Месяц')], help_text='Оставьте пустым, если стоимость не зависит от переодичности', max_length=1, verbose_name='В срок')),
            ],
            options={
                'verbose_name': 'Единица измерения услуги',
                'verbose_name_plural': 'Единицы измерения услуг',
            },
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.RemoveField(
            model_name='servicetariff',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления услуги', verbose_name='В архиве'),
        ),
        migrations.AddField(
            model_name='service',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='time_for_service',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество рабочего времени (мин)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.CharField(choices=[('SB', 'Социально-бытовые услуги'), ('ME', 'Социально-медицинские услуги'), ('PS', 'Социально-психологические услуги'), ('ED', 'Социально-педагогические услуги'), ('WO', 'Социально-трудовые услуги'), ('LA', 'Социально-правовые услуги'), ('CO', 'Услуги в целях повышения коммуникативного потенциала получателей социальных услуг имеющих ограничения жизнедеятельности, в том числе детей-инвалидов'), ('QU', 'Срочные социальные услуги'), ('OT', '-Прочие')], max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.DeleteModel(
            name='ServiceTariff',
        ),
        migrations.AddField(
            model_name='service',
            name='measurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_work.ServiceMeasurement', verbose_name='Единица измерения (периодизация)'),
            preserve_default=False,
        ),
    ]
