# Generated by Django 2.1.7 on 2020-02-14 16:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200214_1607'),
        ('social_work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Включенная в ИППСУ услуга',
                'verbose_name_plural': 'Включенные в ИППСУ услуги',
            },
        ),
        migrations.CreateModel(
            name='IPPSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False, help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления услуги', verbose_name='В архиве')),
                ('serviced_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson', verbose_name='Обслуживаемый')),
                ('social_worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.WorkerPosition', verbose_name='Социальный работник')),
            ],
            options={
                'verbose_name': 'ИППСУ',
                'verbose_name_plural': 'ИППСУ',
            },
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата оказания')),
                ('type_of_service', models.CharField(blank=True, choices=[('G', 'Гарантированная'), ('A', 'Дополнительная'), ('P', 'Платная')], max_length=1, verbose_name='Тип услуги')),
                ('ippsu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.IPPSU', verbose_name='ИППСУ')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Единица измерения')),
                ('statement', models.CharField(choices=[('l', 'менее/до/не более'), ('e', 'ровно'), ('g', 'более/от/свыше'), ('d', 'Без условий')], default='d', max_length=1, verbose_name='Условие')),
                ('count', models.IntegerField(default=1, verbose_name='Количество')),
                ('period', models.CharField(choices=[('D', 'день'), ('W', 'неделю'), ('M', 'месяц'), ('N', 'отсутствует')], default='N', max_length=1, verbose_name='В срок')),
            ],
            options={
                'verbose_name': 'Единица измерения услуги',
                'verbose_name_plural': 'Единицы измерения услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False, help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления услуги', verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Перечень услуг',
                'verbose_name_plural': 'Перечни услуг',
            },
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.RemoveField(
            model_name='servicejournal',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='servicejournal',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicejournal',
            name='serviced',
        ),
        migrations.RemoveField(
            model_name='servicetariff',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='place',
            field=models.CharField(choices=[('H', 'на дому'), ('O', 'в организации (полустационар)'), ('-', 'повсеместно')], default='-', max_length=1, verbose_name='Место оказания'),
        ),
        migrations.AddField(
            model_name='service',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='time_for_service',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество рабочего времени (мин)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.CharField(choices=[('SB', 'Социально-бытовые услуги'), ('ME', 'Социально-медицинские услуги'), ('PS', 'Социально-психологические услуги'), ('ED', 'Социально-педагогические услуги'), ('WO', 'Социально-трудовые услуги'), ('LA', 'Социально-правовые услуги'), ('CO', 'Услуги в целях повышения коммуникативного потенциала получателей социальных услуг имеющих ограничения жизнедеятельности, в том числе детей-инвалидов'), ('QU', 'Срочные социальные услуги'), ('OT', '-Прочие'), ('UN', 'Не указано')], default='UN', max_length=2, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='service',
            name='type_of_service',
            field=models.CharField(choices=[('G', 'Гарантированная'), ('A', 'Дополнительная'), ('P', 'Платная')], default='UN', max_length=1, verbose_name='Тип'),
        ),
        migrations.DeleteModel(
            name='ServiceJournal',
        ),
        migrations.DeleteModel(
            name='ServiceTariff',
        ),
        migrations.AddField(
            model_name='providedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.Service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='IPPSU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.IPPSU', verbose_name='ИППСУ'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_work.Service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='service',
            name='measurement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_work.ServiceMeasurement', verbose_name='Единица измерения (периодизация)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='services_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_work.ServicesList', verbose_name='Перечень услуг'),
            preserve_default=False,
        ),
    ]
