# Generated by Django 2.1.7 on 2020-02-25 13:40

import applications.core.utils.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_work', '0002_auto_20200214_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ippsu',
            name='date_to',
            field=models.DateField(default=applications.core.utils.datetime.later_3_years, verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='ippsu',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления ИППСУ', verbose_name='В архиве'),
        ),
    ]
