# Generated by Django 2.1.7 on 2020-03-11 16:33

import applications.social_work.enums
import choicesenum.django.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_work', '0002_auto_20200311_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='statement',
            field=choicesenum.django.fields.EnumCharField(default='eq', enum=applications.social_work.enums.StatementEnum, max_length=2, verbose_name='Логический оператор'),
        ),
    ]
