# Generated by Django 3.0.5 on 2020-04-08 17:44

import datetime

from django.db import migrations, models

import utils.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPPSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(default=utils.datetime.later_3_years, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False,
                                                    help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления ИППСУ',
                                                    verbose_name='В архиве')),
                ('included_services',
                 models.ManyToManyField(blank=True, to='services.Service', verbose_name='Включенные услуги')),
            ],
            options={
                'verbose_name': 'ИППСУ',
                'verbose_name_plural': 'ИППСУ',
            },
        ),
    ]
