# Generated by Django 3.0.4 on 2020-03-25 22:04

import datetime

from django.db import migrations, models

import utils.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncludedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Включенная в ИППСУ услуга',
                'verbose_name_plural': 'Включенные в ИППСУ услуги',
            },
        ),
        migrations.CreateModel(
            name='IPPSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(default=utils.datetime.later_3_years, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False,
                                                    help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления ИППСУ',
                                                    verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'ИППСУ',
                'verbose_name_plural': 'ИППСУ',
            },
        ),
    ]
