# Generated by Django 3.0.4 on 2020-03-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('people', '0001_initial'),
        ('ippsu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippsu',
            name='serviced_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ServicedPerson',
                                    verbose_name='Обслуживаемый'),
        ),
        migrations.AddField(
            model_name='ippsu',
            name='social_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.WorkerPosition',
                                    verbose_name='Социальный работник'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='IPPSU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_services',
                                    to='ippsu.IPPSU', verbose_name='ИППСУ'),
        ),
        migrations.AddField(
            model_name='includedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service',
                                    verbose_name='Услуга'),
        ),
    ]
