# Generated by Django 3.0.4 on 2020-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('services', '0002_auto_20200325_2220'),
        ('ippsu', '0002_auto_20200325_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippsu',
            name='included_services',
            field=models.ManyToManyField(blank=True, null=True, to='services.Service',
                                         verbose_name='Включенные услуги'),
        ),
        migrations.DeleteModel(
            name='IncludedService',
        ),
    ]
