# Generated by Django 2.1.7 on 2019-06-03 18:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания')),
                ('date_of_update', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('A', 'Опубликована'), ('W', 'Черновик'), ('D', 'Удалена')], max_length=1, verbose_name='Статус')),
                ('slugify', models.CharField(max_length=256, verbose_name='Адресс')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
