# Generated by Django 2.1.7 on 2019-06-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slugify',
            field=models.CharField(max_length=256, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('A', 'Опубликована'), ('W', 'Черновик'), ('D', 'Удалена')], default='W', max_length=1, verbose_name='Статус'),
        ),
    ]
