# Generated by Django 2.1.7 on 2019-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190604_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slugify',
            field=models.CharField(blank=True, default='sluger', max_length=256, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
