# Generated by Django 2.1.7 on 2019-06-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190604_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slugify',
            field=models.CharField(max_length=256, verbose_name='URL'),
        ),
    ]
