# Generated by Django 2.1.7 on 2019-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190604_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slugify',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='URL'),
        ),
    ]
