# Generated by Django 2.1.7 on 2019-06-03 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190604_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='slugify',
            new_name='slug_url',
        ),
    ]
