# Generated by Django 2.1.7 on 2019-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190604_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug_url',
            field=models.SlugField(default=1, max_length=350, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
