# Generated by Django 2.1.7 on 2019-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20190604_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_of_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug_url',
            field=models.SlugField(editable=False, max_length=350, unique=True, verbose_name='URL'),
        ),
    ]
