# Generated by Django 3.0.4 on 2020-03-11 18:32

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models

import applications.documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('social_work', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(editable=False,
                                          storage=django.core.files.storage.FileSystemStorage(location='/media/docs'),
                                          upload_to='', verbose_name='Файл')),
                ('additional_journal', models.ForeignKey(blank=True,
                                                         help_text='Дополнительный журнал. Добавьте, если ИППСУ заканчивается в середине месяца',
                                                         null=True, on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='socialact_additional',
                                                         to='social_work.ProvidedServiceJournal',
                                                         verbose_name='Дополнительный журнал оказанных социальных услуг')),
                ('avg_per_capita_income',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AveragePerCapitaIncome',
                                   verbose_name='Средний душевой доход за 12 месяцев')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialact',
                                              to='social_work.ProvidedServiceJournal',
                                              verbose_name='Журнал оказанных социальных услуг')),
                ('living_wage', models.ForeignKey(default=applications.documents.models.last_living_wage,
                                                  on_delete=django.db.models.deletion.CASCADE, to='core.LivingWage',
                                                  verbose_name='Полтора прожиточных минимума для пенсионера')),
            ],
            options={
                'verbose_name': 'Акты социальных услуг',
                'verbose_name_plural': 'Акт социальных услуг',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaidAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(editable=False,
                                          storage=django.core.files.storage.FileSystemStorage(location='/media/docs'),
                                          upload_to='', verbose_name='Файл')),
                ('additional_journal', models.ForeignKey(blank=True,
                                                         help_text='Дополнительный журнал. Добавьте, если ИППСУ заканчивается в середине месяца',
                                                         null=True, on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='paidact_additional',
                                                         to='social_work.ProvidedServiceJournal',
                                                         verbose_name='Дополнительный журнал оказанных социальных услуг')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidact',
                                              to='social_work.ProvidedServiceJournal',
                                              verbose_name='Журнал оказанных социальных услуг')),
            ],
            options={
                'verbose_name': 'Акты платных услуг',
                'verbose_name_plural': 'Акт платных услуг',
                'abstract': False,
            },
        ),
    ]
