# Generated by Django 3.0.5 on 2020-04-08 17:44

import django.db.models.deletion
from django.db import migrations, models

import utils.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=9,
                                            verbose_name='Размер предельной величины среднедушевого дохода')),
                ('date_to', models.DateField(default=utils.datetime.month_end, verbose_name='По дате')),
            ],
            options={
                'verbose_name': 'Прожиточный минимум',
                'verbose_name_plural': 'Прожиточный минимум',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1024, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Льготная категория',
                'verbose_name_plural': 'Льготные категории',
            },
        ),
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=4, verbose_name='Серия')),
                ('number', models.CharField(max_length=6, verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('serviced_person',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.ServicedPerson',
                                      verbose_name='Обслуживаемый гражданин')),
            ],
            options={
                'verbose_name': 'Пасспортные данные',
                'verbose_name_plural': 'Пасспортные данные',
            },
        ),
        migrations.CreateModel(
            name='AveragePerCapitaIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to', models.DateField(default=utils.datetime.month_end, verbose_name='По дате')),
                ('avg_income', models.DecimalField(decimal_places=2, max_digits=9,
                                                   verbose_name='Среднедушевой доход за последние 12 месяцев')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ServicedPerson',
                                   verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Среднедушвые доходы за 12 месяцев',
                'verbose_name_plural': 'Среднедушвой доход за 12 месяцев',
            },
        ),
    ]
