# Generated by Django 2.1.7 on 2019-05-26 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название должности')),
                ('purpose', models.TextField(blank=True, max_length=1024, verbose_name='Назначение должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='ServicedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('LI', 'Жив'), ('DE', 'Мертв'), ('ME', 'На лечении'), ('OU', 'Выписан')], max_length=2, verbose_name='Статус')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Обслуживаемый',
                'verbose_name_plural': 'Обслуживаемые',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('surname', models.CharField(blank=True, max_length=256, verbose_name='Фамилия')),
                ('is_man', models.BooleanField(default=False, verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('FI', 'Уволен'), ('WO', 'Работает'), ('VA', 'В отпуске')], max_length=2, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(default=datetime.datetime.now, verbose_name='Дата устройства на должность')),
                ('dismissal_date', models.DateField(null=True, verbose_name='Дата увольнения с должности')),
                ('rate', models.FloatField(default=1, verbose_name='Ставка')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='core.Worker', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='core.Position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Ставка сотрудника',
                'verbose_name_plural': 'Ставки сотрудников',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='positions',
            field=models.ManyToManyField(related_name='Workers', through='core.WorkerPosition', to='core.Position'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
