# Generated by Django 3.0.4 on 2020-03-11 18:32

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import applications.core.utils.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LivingWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=9,
                                            verbose_name='Размер предельной величины среднедушевого дохода')),
                ('date_to',
                 models.DateField(default=applications.core.utils.datetime.month_end, verbose_name='По дате')),
            ],
            options={
                'verbose_name': 'Прожиточный минимум',
                'verbose_name_plural': 'Прожиточный минимум',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1024, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Льготная категория',
                'verbose_name_plural': 'Льготные категории',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='F', max_length=1,
                                            verbose_name='Пол')),
                ('date_of_birth',
                 models.DateField(help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', verbose_name='Дата рождения')),
                ('status', models.CharField(
                    choices=[('FI', 'Уволен'), ('WO', 'Работает'), ('ME', 'На больничном'), ('VA', 'В отпуске')],
                    default='WO', max_length=2, verbose_name='Статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                              verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WorkerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(
                    choices=[('C', 'Заведующий отделением'), ('S', 'Социальный работник'), ('N', 'Сиделка'),
                             ('R', 'Администратор отделения')], default='S', max_length=1, verbose_name='Должность')),
                ('date_of_appointment',
                 models.DateField(default=datetime.datetime.now, verbose_name='Дата устройства на должность')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения с должности')),
                ('rate', models.FloatField(default=1, verbose_name='Ставка')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership',
                                             to='core.Worker', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ставка сотрудника',
                'verbose_name_plural': 'Ставки сотрудников',
            },
        ),
        migrations.CreateModel(
            name='ServicedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=128, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='F', max_length=1, verbose_name='Пол')),
                ('date_of_birth', models.DateField(help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', verbose_name='Дата рождения')),
                ('location', models.CharField(choices=[('HE', 'На обслуживании'), ('ME', 'На лечении'), ('OU', 'В поездке'), ('LE', 'Покинул отделение'), ('DE', 'Умерший')], default='HE', max_length=2, verbose_name='Местонахождение')),
                ('contract_number', models.CharField(default='№ ', max_length=128, verbose_name='Номер договора')),
                ('date_of_income', models.DateField(default=datetime.datetime.now, verbose_name='Дата заключения договора')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('date_of_departure', models.DateField(blank=True, null=True, verbose_name='Дата ухода')),
                ('privileges', models.ManyToManyField(blank=True, to='core.Privilege', verbose_name='Льготные категории')),
            ],
            options={
                'verbose_name': 'Обслуживаемый',
                'verbose_name_plural': 'Обслуживаемые',
            },
        ),
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=4, verbose_name='Серия')),
                ('number', models.CharField(max_length=6, verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
                ('serviced_person',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson',
                                      verbose_name='Обслуживаемый гражданин')),
            ],
            options={
                'verbose_name': 'Пасспортные данные',
                'verbose_name_plural': 'Пасспортные данные',
            },
        ),
        migrations.CreateModel(
            name='AveragePerCapitaIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to',
                 models.DateField(default=applications.core.utils.datetime.month_end, verbose_name='По дате')),
                ('avg_income', models.DecimalField(decimal_places=2, max_digits=9,
                                                   verbose_name='Среднедушевой доход за последние 12 месяцев')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson',
                                   verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Среднедушвые доходы за 12 месяцев',
                'verbose_name_plural': 'Среднедушвой доход за 12 месяцев',
            },
        ),
    ]
