# Generated by Django 2.1.7 on 2019-06-05 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedperson',
            name='status',
            field=models.CharField(choices=[('LI', 'Жив'), ('DE', 'Мертв'), ('ME', 'На лечении'), ('OU', 'В поездке'), ('LE', 'Выписан')], max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('FI', 'Уволен'), ('WO', 'Работает'), ('ME', 'Больничный'), ('VA', 'В отпуске')], default='WO', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
