# Generated by Django 2.1.7 on 2019-06-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190606_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='is_man',
            new_name='gender',
        ),
    ]
