# Generated by Django 2.1.7 on 2019-06-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('core', '0005_auto_20190606_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Группа пользователей'),
            preserve_default=False,
        ),
    ]
