# Generated by Django 2.1.7 on 2019-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_position_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerposition',
            name='dismissal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения с должности'),
        ),
    ]
