# Generated by Django 2.1.7 on 2019-06-06 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190606_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='positions',
        ),
    ]
