# Generated by Django 2.1.7 on 2019-06-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_worker_positions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerposition',
            old_name='person',
            new_name='worker',
        ),
    ]
