# Generated by Django 2.1.7 on 2019-09-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190607_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='F', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='date_of_birth',
            field=models.DateField(help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', null=True, verbose_name='Дата рождения'),
        ),
    ]
