# Generated by Django 2.1.7 on 2020-02-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190912_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=4, verbose_name='Серия')),
                ('number', models.CharField(max_length=6, verbose_name='Номер')),
                ('date_of_issue', models.DateField(verbose_name='Дата выдачи')),
            ],
            options={
                'verbose_name': 'Пасспортные данные',
                'verbose_name_plural': 'Пасспортные данные',
            },
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название категории')),
                ('sale_guaranteed', models.FloatField(default=0, verbose_name='Скидка на гарантированные услуги')),
                ('sale_additional', models.FloatField(default=0, verbose_name='Скидка на дополнительные услуги')),
            ],
            options={
                'verbose_name': 'Льготная категория',
                'verbose_name_plural': 'Льготные категории',
            },
        ),
        migrations.RemoveField(
            model_name='servicedperson',
            name='status',
        ),
        migrations.AddField(
            model_name='servicedperson',
            name='date_of_departure',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ухода'),
        ),
        migrations.AddField(
            model_name='servicedperson',
            name='location',
            field=models.CharField(choices=[('HE', 'На обслуживании'), ('ME', 'На лечении'), ('OU', 'В поездке')], default='HE', max_length=2, verbose_name='Местонахождение'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('FI', 'Уволен'), ('WO', 'Работает'), ('ME', 'На больничном'), ('VA', 'В отпуске')], default='WO', max_length=2, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='passportdata',
            name='serviced_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson', verbose_name='Обслуживаемый гражданин'),
        ),
        migrations.AddField(
            model_name='servicedperson',
            name='privileges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Privilege', verbose_name='Льготные категории'),
        ),
    ]
