# Generated by Django 2.1.7 on 2020-02-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200214_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='title',
            field=models.TextField(max_length=1024, verbose_name='Название категории'),
        ),
    ]
