# Generated by Django 2.1.7 on 2020-02-14 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200214_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilege',
            name='sale_additional',
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='sale_guaranteed',
        ),
    ]
