# Generated by Django 2.1.7 on 2020-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200214_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedperson',
            name='privileges',
        ),
        migrations.AddField(
            model_name='servicedperson',
            name='privileges',
            field=models.ManyToManyField(null=True, to='core.Privilege', verbose_name='Льготные категории'),
        ),
    ]
