# Generated by Django 2.1.7 on 2020-02-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200217_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedperson',
            name='privileges',
            field=models.ManyToManyField(blank=True, to='core.Privilege', verbose_name='Льготные категории'),
        ),
    ]
