# Generated by Django 2.1.7 on 2020-02-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200217_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedperson',
            name='location',
            field=models.CharField(choices=[('HE', 'На обслуживании'), ('ME', 'На лечении'), ('OU', 'В поездке'), ('LE', 'Покинул отделение'), ('DE', 'Умерший')], default='HE', max_length=2, verbose_name='Местонахождение'),
        ),
    ]
