# Generated by Django 2.1.7 on 2020-02-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200218_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedperson',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='F', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='surname',
            field=models.CharField(blank=True, max_length=256, verbose_name='Фамилия'),
        ),
    ]
