# Generated by Django 2.1.7 on 2020-02-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200223_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedperson',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='patronymic',
            field=models.CharField(max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='servicedperson',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(max_length=128, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
        ),
    ]
