# Generated by Django 2.1.7 on 2020-02-23 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200223_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedperson',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 2, 23, 20, 48, 58, 587827), help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2020, 2, 23, 20, 49, 10, 468506), help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
