# Generated by Django 3.0.4 on 2020-03-25 22:04

import datetime

import django.core.validators
import django.db.models.manager
from django.db import migrations, models

import utils.datetime


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('ippsu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidedServiceJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=utils.datetime.month_start, verbose_name='Период от')),
                ('date_to', models.DateField(default=utils.datetime.month_end, verbose_name='Период до')),
                ('ippsu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='provided_services_journals', to='ippsu.IPPSU',
                                            verbose_name='ИППСУ')),
            ],
            options={
                'verbose_name': 'Журнал оказанных услуг',
                'verbose_name_plural': 'Журналы оказанных услуг',
            },
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата оказания')),
                ('type_of_service', models.CharField(
                    choices=[('G', 'гарантированная'), ('A', 'дополнительная'), ('P', 'платная'),
                             ('F', 'платная (гарантия)'), ('C', '-вычисляется-')], default='C', editable=False,
                    max_length=1, verbose_name='Тип')),
                ('volume', models.FloatField(default=1.0, verbose_name='Оказанный объем услуги')),
                ('quantity',
                 models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)],
                                                  verbose_name='Количество услуг')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services',
                                              to='providing.ProvidedServiceJournal',
                                              verbose_name='Журнал оказанных услуг')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service',
                                              verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Оказанная услуга',
                'verbose_name_plural': 'Оказанные услуги',
            },
            managers=[
                ('by_type', django.db.models.manager.Manager()),
            ],
        ),
    ]
