# Generated by Django 2.1.7 on 2020-02-03 16:41

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ('core', '0011_auto_20200203_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(
                    choices=[('C', 'Холодная вода'), ('W', 'Горячая вода'), ('G', 'Газосноснабжение'),
                             ('E', 'Электричество'), ('O', 'Отопление')], max_length=1, verbose_name='Тип счётчика')),
                ('serial_number', models.CharField(max_length=64, verbose_name='Серийный номер счетчика')),
            ],
            options={
                'verbose_name': 'Счётчик',
                'verbose_name_plural': 'Счётчики',
            },
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=1, max_digits=15, verbose_name='Показания')),
                ('date_of', models.DateField(default=datetime.datetime.now, verbose_name='Дата показания')),
                ('receptionist',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition',
                                   verbose_name='Ответственный администратор')),
            ],
            options={
                'verbose_name': 'Показания счётчика',
                'verbose_name_plural': 'Показания счётчиков',
            },
        ),
        migrations.CreateModel(
            name='Overnight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Ночёвка',
                'verbose_name_plural': 'Ночёвки',
            },
        ),
        migrations.CreateModel(
            name='OvernightJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Период от')),
                ('date_to', models.DateTimeField(verbose_name='Период до')),
            ],
            options={
                'verbose_name': 'Журнал ночующих в отделении',
                'verbose_name_plural': 'Журналы ночующих в отделении',
            },
        ),
        migrations.CreateModel(
            name='SealingMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(default=datetime.datetime.now, verbose_name='Опломбирован')),
                ('date_to', models.DateField(verbose_name='Опломбирование действительно до')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.Meter',
                                            verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Опломбировки счётчиков',
                'verbose_name_plural': 'Опломбировка счётчика',
            },
        ),
        migrations.CreateModel(
            name='ServicedPersonOvernight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.NightShift',
                                                verbose_name='Ночь')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServicedPerson',
                                   verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Ночующий в отделении обслуживаемый',
                'verbose_name_plural': 'Ночующие в отделении обслуживаемые',
            },
        ),
        migrations.CreateModel(
            name='UtilityBil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(default=datetime.datetime.now, verbose_name='Дата начисления')),
                ('total', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Сумма')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition',
                                            verbose_name='Ответственный заведующий')),
                ('sealing_meter',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receptionist.SealingMeter',
                                   verbose_name='Опломбировка')),
            ],
            options={
                'verbose_name': 'Квитанция коммунальных услуг',
                'verbose_name_plural': 'Квитанции коммунальных услуг',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало визита')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Конец визита')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Имя')),
                ('commentary', models.TextField(max_length=2048, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='VisitorJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Период от')),
                ('date_to', models.DateTimeField(verbose_name='Период до')),
            ],
            options={
                'verbose_name': 'Журнал посетителей',
                'verbose_name_plural': 'Журналы посетителей',
            },
        ),
        migrations.CreateModel(
            name='VisitorOvernight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overnight.NightShift',
                                                verbose_name='Ночь')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.Visitor',
                                   verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Ночующий в отделении посетитель',
                'verbose_name_plural': 'Ночующие в отделении посетители',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.VisitorJournal',
                                    verbose_name='Журнал посетителей'),
        ),
        migrations.AddField(
            model_name='visit',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition',
                                    verbose_name='Ответственный администратор'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.Visitor',
                                    verbose_name='Посетитель'),
        ),
        migrations.AddField(
            model_name='overnight',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.OvernightJournal',
                                    verbose_name='Журнал ночующих в отделении'),
        ),
        migrations.AddField(
            model_name='meterdata',
            name='sealing_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist.SealingMeter',
                                    verbose_name='Опломбировка'),
        ),
    ]
