# Generated by Django 2.1.7 on 2020-02-03 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdata',
            name='receptionist',
        ),
        migrations.RemoveField(
            model_name='meterdata',
            name='sealing_meter',
        ),
        migrations.RemoveField(
            model_name='overnight',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='sealingmeter',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='servicedpersonovernight',
            name='overnight',
        ),
        migrations.RemoveField(
            model_name='servicedpersonovernight',
            name='serviced_person',
        ),
        migrations.RemoveField(
            model_name='utilitybil',
            name='chief',
        ),
        migrations.RemoveField(
            model_name='utilitybil',
            name='sealing_meter',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='receptionist',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visitor',
        ),
        migrations.RemoveField(
            model_name='visitorovernight',
            name='overnight',
        ),
        migrations.RemoveField(
            model_name='visitorovernight',
            name='serviced_person',
        ),
        migrations.DeleteModel(
            name='Meter',
        ),
        migrations.DeleteModel(
            name='MeterData',
        ),
        migrations.DeleteModel(
            name='Overnight',
        ),
        migrations.DeleteModel(
            name='OvernightJournal',
        ),
        migrations.DeleteModel(
            name='SealingMeter',
        ),
        migrations.DeleteModel(
            name='ServicedPersonOvernight',
        ),
        migrations.DeleteModel(
            name='UtilityBil',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='VisitorJournal',
        ),
        migrations.DeleteModel(
            name='VisitorOvernight',
        ),
    ]
