# Generated by Django 2.1.7 on 2020-02-03 17:30

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # ('core', '0012_auto_20200203_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(
                    choices=[('C', 'Холодная вода'), ('W', 'Горячая вода'), ('G', 'Газосноснабжение'),
                             ('E', 'Электричество'), ('O', 'Отопление')], max_length=1, verbose_name='Тип счётчика')),
                ('serial_number', models.CharField(max_length=64, verbose_name='Серийный номер счетчика')),
            ],
            options={
                'verbose_name': 'Счётчик',
                'verbose_name_plural': 'Счётчики',
            },
        ),
        migrations.CreateModel(
            name='MeterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=1, max_digits=15, verbose_name='Показания')),
                ('date_of', models.DateField(default=datetime.datetime.now, verbose_name='Дата показания')),
                ('receptionist',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition',
                                   verbose_name='Ответственный администратор')),
            ],
            options={
                'verbose_name': 'Показания счётчика',
                'verbose_name_plural': 'Показания счётчиков',
            },
        ),
        migrations.CreateModel(
            name='SealingMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(default=datetime.datetime.now, verbose_name='Опломбирован')),
                ('date_to', models.DateField(verbose_name='Опломбирование действительно до')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.Meter',
                                            verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Опломбировки счётчиков',
                'verbose_name_plural': 'Опломбировка счётчика',
            },
        ),
        migrations.CreateModel(
            name='UtilityBil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateField(default=datetime.datetime.now, verbose_name='Дата начисления')),
                ('total', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Сумма')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition',
                                            verbose_name='Ответственный заведующий')),
                ('sealing_meter',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meter.SealingMeter',
                                   verbose_name='Опломбировка')),
            ],
            options={
                'verbose_name': 'Квитанция коммунальных услуг',
                'verbose_name_plural': 'Квитанции коммунальных услуг',
            },
        ),
        migrations.AddField(
            model_name='meterdata',
            name='sealing_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.SealingMeter',
                                    verbose_name='Опломбировка'),
        ),
    ]
