# Generated by Django 3.0.4 on 2020-03-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('meter', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybil',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.WorkerPosition',
                                    verbose_name='Ответственный заведующий'),
        ),
        migrations.AddField(
            model_name='utilitybil',
            name='sealing_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meter.SealingMeter',
                                    verbose_name='Опломбировка'),
        ),
        migrations.AddField(
            model_name='sealingmeter',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.Meter',
                                    verbose_name='Счётчик'),
        ),
        migrations.AddField(
            model_name='meterdata',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.WorkerPosition',
                                    verbose_name='Ответственный администратор'),
        ),
        migrations.AddField(
            model_name='meterdata',
            name='sealing_meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.SealingMeter',
                                    verbose_name='Опломбировка'),
        ),
    ]
