# Generated by Django 3.0.4 on 2020-03-21 22:11

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='От')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='До')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('diagnose', models.TextField(blank=True, null=True, verbose_name='Диагноз')),
            ],
            options={
                'verbose_name': 'Больничный',
                'verbose_name_plural': 'Больничные',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='От')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='До')),
                ('commentary', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Поездка обслуживаемого',
                'verbose_name_plural': 'Поездки обслуживаемых',
            },
        ),
    ]
