# Generated by Django 3.0.4 on 2020-03-25 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('movements', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='serviced_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ServicedPerson',
                                    verbose_name='Обслуживаемый'),
        ),
        migrations.AddField(
            model_name='travel',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='people.Visitor', verbose_name='Родственник'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='serviced_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ServicedPerson',
                                    verbose_name='Обслуживаемый'),
        ),
    ]
