# Generated by Django 3.0.4 on 2020-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period',
                 models.IntegerField(choices=[(None, '-Неопределенно-'), (1, 'день'), (7, 'неделю'), (31, 'месяц')],
                                     default=31, verbose_name='Периодичность')),
                ('limit', models.IntegerField(default=1,
                                              help_text='Укажите ограничение (к примеру не более одного или не более двух',
                                              verbose_name='Ограничение')),
            ],
            options={
                'verbose_name': 'Условие ограничения периодичности предоставления услуги',
                'verbose_name_plural': 'Условия ограничения периодичности предоставления услуг',
            },
        ),
        migrations.CreateModel(
            name='VolumeLimitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.FloatField(default=1,
                                            help_text='Укажите ограничение (к примеру не более 1 (кв.м) или не более двух (изделий)',
                                            unique=True, verbose_name='Ограничение')),
            ],
            options={
                'verbose_name': 'Условие ограничения объема предоставления услуги',
                'verbose_name_plural': 'Условия ограничения объема предоставления услуг',
            },
        ),
    ]
