# Generated by Django 3.0.4 on 2020-03-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('serviced_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedperson',
            name='privileges',
            field=models.ManyToManyField(blank=True, to='serviced_data.Privilege', verbose_name='Льготные категории'),
        ),
    ]
