# Generated by Django 3.0.5 on 2020-04-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviced_data', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedperson',
            name='privileges',
            field=models.ManyToManyField(blank=True, to='serviced_data.Privilege', verbose_name='Льготные категории'),
        ),
    ]
