# Generated by Django 3.0.4 on 2020-03-25 22:04

import datetime

import django.db.models.deletion
from django.db import migrations, models

import applications.social_work.limitations.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('limitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения услуги',
                'verbose_name_plural': 'Единицы измерения услуг',
            },
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=datetime.datetime.now, verbose_name='Действует от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Действителен до')),
                ('is_archived', models.BooleanField(default=False,
                                                    help_text='Для совместимости со старыми отчетами, установите флаг, вместо удаления услуги',
                                                    verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'Перечень услуг',
                'verbose_name_plural': 'Перечни услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=512, verbose_name='Наименование')),
                ('type_of_service', models.CharField(
                    choices=[('G', 'гарантированная'), ('A', 'дополнительная'), ('P', 'платная'),
                             ('F', 'платная (гарантия)'), ('C', '-вычисляется-')], default='P', max_length=1,
                    verbose_name='Тип')),
                ('service_category', models.CharField(blank=True,
                                                      choices=[(None, 'Не указано'), ('SB', 'Социально-бытовые услуги'),
                                                               ('ME', 'Социально-медицинские услуги'),
                                                               ('PS', 'Социально-психологические услуги'),
                                                               ('ED', 'Социально-педагогические услуги'),
                                                               ('WO', 'Социально-трудовые услуги'),
                                                               ('LA', 'Социально-правовые услуги'), ('CO',
                                                                                                     'Услуги в целях повышения коммуникативного потенциала получателей социальных услуг имеющих ограничения жизнедеятельности, в том числе детей-инвалидов'),
                                                               ('QU', 'Срочные социальные услуги'), ('OT', '-Прочие')],
                                                      default=None, max_length=2, null=True, verbose_name='Категория')),
                ('tax', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость')),
                ('time_for_service',
                 models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество рабочего времени (мин)')),
                ('place', models.CharField(
                    choices=[('H', 'на дому'), ('O', 'в организации (полустационар)'), ('-', 'повсеместно')],
                    default='-', max_length=1, verbose_name='Место оказания')),
                ('measurement',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceMeasurement',
                                   verbose_name='Единица измерения')),
                ('period_limitation', models.ForeignKey(default=None,
                                                        help_text="Установите значение если услуга ограничена периодичностью оказания (например 'не более 2 раз в неделю'",
                                                        null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                        to='limitations.PeriodLimitation',
                                                        verbose_name='Ограничение периодичности')),
                ('services_list',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicesList',
                                   verbose_name='Перечень услуг')),
                ('volume_limitation',
                 models.ForeignKey(default=applications.social_work.limitations.models.get_one_volume,
                                   help_text="Устаноивте значение если объем одной оказываемой услуги ограничен (например 'не более 50 кв.м.')",
                                   on_delete=django.db.models.deletion.SET_DEFAULT, to='limitations.VolumeLimitation',
                                   verbose_name='Ограничение объема')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
