# Generated by Django 3.0.4 on 2020-03-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('limitations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='period_limitation',
            field=models.ForeignKey(blank=True, default=None,
                                    help_text="Установите значение если услуга ограничена периодичностью оказания (например 'не более 2 раз в неделю'",
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='limitations.PeriodLimitation', verbose_name='Ограничение периодичности'),
        ),
    ]
