# Generated by Django 3.0.5 on 2020-04-08 17:44

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Дата')),
                ('receptionist',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.WorkerPosition',
                                   verbose_name='Ответственный администратор')),
            ],
            options={
                'verbose_name': 'Ночная смена',
                'verbose_name_plural': 'Ночные смены',
            },
        ),
        migrations.CreateModel(
            name='VisitorOvernight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleepover.NightShift',
                                                verbose_name='Ночь')),
                ('serviced_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Visitor',
                                                      verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Ночующий в отделении посетитель',
                'verbose_name_plural': 'Ночующие в отделении посетители',
            },
        ),
        migrations.CreateModel(
            name='ServicedPersonOvernight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overnight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleepover.NightShift',
                                                verbose_name='Ночь')),
                ('serviced_person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ServicedPerson',
                                   verbose_name='Обслуживаемый')),
            ],
            options={
                'verbose_name': 'Ночующий в отделении обслуживаемый',
                'verbose_name_plural': 'Ночующие в отделении обслуживаемые',
            },
        ),
    ]
