# Generated by Django 3.0.5 on 2020-04-08 17:44

import datetime

import django.db.models.deletion
from django.db import migrations, models

import utils.datetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало визита')),
                ('date_to', models.DateTimeField(blank=True, default=utils.datetime.later_two_hours, null=True,
                                                 verbose_name='Конец визита')),
                ('receptionist',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.WorkerPosition',
                                   verbose_name='Ответственный администратор')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Visitor',
                                              verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
