# Generated by Django 2.1.7 on 2020-02-03 17:30

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0012_auto_20200203_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Начало визита')),
                ('date_to', models.DateTimeField(blank=True, null=True, verbose_name='Конец визита')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Имя')),
                ('commentary', models.TextField(max_length=2048, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Посетитель',
                'verbose_name_plural': 'Посетители',
            },
        ),
        migrations.CreateModel(
            name='VisitorJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of', models.DateTimeField(default=datetime.datetime.now, verbose_name='Период от')),
                ('date_to', models.DateTimeField(verbose_name='Период до')),
            ],
            options={
                'verbose_name': 'Журнал посетителей',
                'verbose_name_plural': 'Журналы посетителей',
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.VisitorJournal',
                                    verbose_name='Журнал посетителей'),
        ),
        migrations.AddField(
            model_name='visit',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerPosition',
                                    verbose_name='Ответственный администратор'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.Visitor',
                                    verbose_name='Посетитель'),
        ),
    ]
