# Generated by Django 2.1.7 on 2020-02-23 19:41

import applications.core.utils.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20200203_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date_to',
            field=models.DateTimeField(blank=True, default=applications.core.utils.datetime.later_two_hours, null=True, verbose_name='Конец визита'),
        ),
    ]
