# Generated by Django 2.1.7 on 2020-02-23 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_auto_20200223_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, help_text='В формате ДД.ММ.ГГГГ (например 27.02.2019', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='F', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='patronymic',
            field=models.CharField(default='Неизвестно', max_length=128, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='surname',
            field=models.CharField(max_length=256, verbose_name='Фамилия'),
        ),
    ]
