# Generated by Django 2.1.7 on 2019-05-17 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=128, verbose_name='Отчество')),
                ('surname', models.CharField(blank=True, max_length=256, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='PersonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(default=datetime.datetime.now, verbose_name='Дата устройства на должность')),
                ('dismissal_date', models.DateField(null=True, verbose_name='Дата увольнения с должности')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='accounts.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название должности')),
                ('purpose', models.TextField(blank=True, max_length=1024, verbose_name='Назначение должности')),
            ],
        ),
        migrations.AddField(
            model_name='personposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='accounts.Position'),
        ),
        migrations.AddField(
            model_name='person',
            name='positions',
            field=models.ManyToManyField(related_name='Persons', through='accounts.PersonPosition', to='accounts.Position'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
